hw 1
myjupyter/AdvCpp pull request #1
Opened 2020-03-10 13:54 UTC by myjupyter

2020-03-15 12:32 UTC, a-badin reviewed
В целом отличный аккуратный код, приятно читать.
Очень радует наличие explicit конструктора, и const методов.

2020-03-15 12:32 UTC, a-badin commented on hw_1/CMakeLists.txt
> +set(CMAKE_CXX_STANDARD 20)
Ты требуешь версию cmake 3.10, а значение CMAKE_CXX_STANDARD 20 появилось только с 3.12.
Надо или понизить до 17, или поменять cmake_minimum_required до 3.12

2020-03-15 12:32 UTC, a-badin commented on hw_1/CMakeLists.txt
> +include_directories(${INC_DIR})
Не влияет на результат, но лучше использовать target_include_directories - в рамках обучения

2020-03-15 12:32 UTC, a-badin commented on hw_1/include/process.h
> +};  // namespace process
В namespace не нужно ;

2020-03-15 12:32 UTC, a-badin commented on hw_1/src/process.cpp
> +    int pipe1[2] = {-1, -1};
В принципе, в инициализации их значением -1 нет смысла, так как ты проверяешь что все прошло хорошо через значение, которое вернул pipe. Если ты оставишь просто pipe1[2]; ничего плохо не произойдет

2020-03-15 12:32 UTC, a-badin commented on hw_1/src/process.cpp
> +        pipe(pipe2) < 0) {
если первый пайп создастся успешно, а второй нет, первый пайп никто не закроет - получим утечку файлового дескриптора

2020-03-15 12:32 UTC, a-badin commented on hw_1/src/process.cpp
> +        stdin = fdopen(STDIN_FILENO, "r");
А зачем вот это открывать? Процесс сам откроет свои stdin/stdout внутри exec

2020-03-15 12:32 UTC, a-badin commented on hw_1/src/process.cpp
> +        char* args[2] = {(char*) path.c_str(), NULL};
Такой код может вызывать проблемы, если компилятор положит константный path в неизменяемую память, а после каста к не const кто-то попробует его поменять. Неизменяемая память встречается редко и только на специфических архитектурах, но все же. Совсем отлично будет сделать копию строки в неконстантный буффер, а так хватит const_cast<char*>(path.c_str()). Разница в том что const_cast легче будет найти в большом проекте.

2020-03-15 12:32 UTC, a-badin commented on hw_1/src/process.cpp
> +    this->close();
this можно не писать

2020-03-15 12:32 UTC, a-badin commented on hw_1/src/process.cpp
> +    if (isWorking()) {
Нужно все же сделать метод wait, который спокойно дожидается завершения процесса. Пусть у нас есть веб-сервер. Мы ходим его ребутнуть, мы готовы подождать пусть даже несколько секунд, но сервер точно всем клиентам отправит страницы целиком, а не сколько получилось пока его не кильнули

2020-03-15 12:32 UTC, a-badin commented on hw_1/src/process.cpp
> +    if (len != this->write(data, len)) {
Получается такой метод, не очень полезнее write. Имелось ввиду поставить счетчик и в цикле дергать write пока не напишем len байт, или ошибка

2020-03-15 12:32 UTC, a-badin commented on hw_1/src/process.cpp
> +    return static_cast<bool>(proc_stdout_stat_);
Зачем тогда делать тип флага enum, если все равно кастим к bool. Если завтра другой программист добавит еще одно состояние в enum, появятся спецэффекты. Четко пишем return stat_ == IS_OPENED

2020-03-15 12:32 UTC, a-badin commented on hw_1/include/process.h
> +enum DescStat {IS_CLOSED = 0, IS_OPENED};
Вот это C-style enum, его минус что он добавляет значения во внешний namespace. То есть вы в main можете написать if (flag != process::IS_CLOSED), такие имена флагов очень общие, они могут быть использованы , например, еще про статус файлов. Будет коллизия имен. В C ставили префикс у значений равный типу енума, DESC_STAT_IS_CLOSED, DESC_STAT_IS_OPENED. Вариант для С++11 enum class {

2020-03-17 17:08 UTC, a-badin commented on hw_1/include/process.h
> +        ~Process();
Можно еще удалить копирование, будет прям отлично

2020-03-17 17:08 UTC, a-badin commented on hw_1/src/main.cpp
> +            char *buffer = new char[s.size() + 1];
Вот прям тут 10 строчками ниже стоит обработчик исключения - если исключение вылетит будет утечка памяти, пусть даже мы сразу закончим работу. У нас же С++, std::vector<char> v(s.size()); v.data()

2020-03-17 17:08 UTC, a-badin commented on hw_1/src/main.cpp
> +        while (proc.isWorking()) {
Раньше программа хоть завершалась, а сейчас как выйти?
Обычно с терминала можно послать EOF через сочетание клавиш Ctrl+D, тогда s будет пустым и программа зациклится. Надо поставить проверку, что !s.empty() - это будет условием выхода

2020-03-17 17:08 UTC, a-badin commented on hw_1/src/process.cpp
> +    return ::wait(&status);
Логичнее, наверное ловить конктретно этот процесс через waitpid, а возвращать статус

2020-03-17 17:29 UTC, a-badin commented on hw_1/src/main.cpp
> +            char *buffer = new char[s.size() + 1];
А с 17 стандарта можно писать в std::string в data()

2020-03-17 18:50 UTC, myjupyter commented on hw_1/CMakeLists.txt
> +set(CMAKE_CXX_STANDARD 20)
+

2020-03-17 18:50 UTC, myjupyter commented on hw_1/CMakeLists.txt
> +include_directories(${INC_DIR})
++

2020-03-17 18:51 UTC, myjupyter commented on hw_1/include/process.h
> +};  // namespace process
++

2020-03-17 18:51 UTC, myjupyter commented on hw_1/src/process.cpp
> +    int pipe1[2] = {-1, -1};
++

2020-03-17 18:51 UTC, myjupyter commented on hw_1/src/process.cpp
> +        pipe(pipe2) < 0) {
++

2020-03-17 18:51 UTC, myjupyter commented on hw_1/src/process.cpp
> +        stdin = fdopen(STDIN_FILENO, "r");
++

2020-03-17 18:52 UTC, myjupyter commented on hw_1/src/process.cpp
> +    this->close();
++

2020-03-17 18:52 UTC, myjupyter commented on hw_1/src/process.cpp
> +    if (len != this->write(data, len)) {
++

2020-03-17 18:52 UTC, myjupyter commented on hw_1/src/process.cpp
> +    return static_cast<bool>(proc_stdout_stat_);
++

2020-03-17 18:52 UTC, myjupyter commented on hw_1/include/process.h
> +enum DescStat {IS_CLOSED = 0, IS_OPENED};
++

2020-03-17 19:21 UTC, myjupyter commented on hw_1/include/process.h
> +        ~Process();
++

2020-03-17 20:56 UTC, myjupyter commented on hw_1/src/main.cpp
> +        while (proc.isWorking()) {
++

2020-03-17 20:57 UTC, myjupyter commented on hw_1/include/process.h
> +        ~Process();
++

2020-03-17 21:24 UTC, myjupyter commented on hw_1/src/process.cpp
> +    return ::wait(&status);
++

2020-03-17 21:24 UTC, myjupyter commented on hw_1/src/main.cpp
> +            char *buffer = new char[s.size() + 1];
++

2020-03-20 18:04 UTC, a-badin commented on hw_1/include/process.h
> +        ~Process();
Тогда и оператор копирования надо удалить

2020-03-20 19:10 UTC, a-badin requested changes

2020-03-20 19:10 UTC, a-badin commented on hw_1/src/main.cpp
> +            proc.read(vec.data(), vec.size());
read может не считать за 1 раз, и выйти раньше

2020-03-20 19:10 UTC, a-badin commented on hw_1/src/process.cpp
> +Process::Process(const std::vector<std::string>& args) {
Ну очень много кода повторяется, давайте сделаем первый аргумент path,а второй вектор строк опциональный - со значением по-умолчанию {}

2020-03-20 19:10 UTC, a-badin commented on hw_1/src/process.cpp
> +        char** argv = static_cast<char**>(calloc(args.size() + 1, sizeof(char*)));
const std::vector<std::string> args{"/bin/echo", "123"};
  std::vector<std::string> copy{args}; // Вариант 1: Копия
  std::vector<char*> data;
  for (std::string& s : copy) {
    data.push_back(s.data()); // Или вместо копии кастить const_cast<char*>(s.data())
  }
  data.push_back(nullptr);
  if (execv(data[0], data.data()) < 0) {
    //throw ...
  }

2020-03-20 19:10 UTC, a-badin commented on hw_1/src/process.cpp
> +    int bytes = ::read(proc_stdout_, data, len);
int 4 байта, а size_t 8

2020-03-20 19:10 UTC, a-badin commented on hw_1/CMakeLists.txt
> +file(WRITE ${LIB_DIR}/CMakeLists.txt "add_library(${LIB_NAME} SHARED ${SRC_DIR}/process.cpp)\n"
Я бы вынес в отдельный файл

2020-03-21 09:43 UTC, myjupyter commented on hw_1/src/process.cpp
> +    int bytes = ::read(proc_stdout_, data, len);
++

2020-03-21 09:50 UTC, myjupyter commented on hw_1/CMakeLists.txt
> +file(WRITE ${LIB_DIR}/CMakeLists.txt "add_library(${LIB_NAME} SHARED ${SRC_DIR}/process.cpp)\n"
++

2020-03-21 09:56 UTC, myjupyter commented on hw_1/src/main.cpp
> +            proc.read(vec.data(), vec.size());
++

2020-03-21 10:33 UTC, myjupyter commented on hw_1/src/process.cpp
> +Process::Process(const std::vector<std::string>& args) {
++

2020-03-21 11:12 UTC, myjupyter commented on hw_1/src/process.cpp
> +        char** argv = static_cast<char**>(calloc(args.size() + 1, sizeof(char*)));
++

2020-03-25 18:14 UTC, a-badin requested changes

2020-03-25 18:14 UTC, a-badin commented on hw_1/src/process.cpp
> +            argv.push_back(const_cast<char*>(arg.c_str()));
тут то уже const_cast не нужен, вы для этого копию args_copy и сделали. Или args_copy надо удалить или const_cast оставить, что вам больше нравится

2020-03-25 18:14 UTC, a-badin commented on hw_1/CMakeLists.txt
> +target_link_libraries(${TARGET_NAME} LINK_PUBLIC ${LIB_NAME})
Я четсно говоря не знаю что делает LINK_PUBLIC, но вижу в документации фразу:
This signature is for compatibility only. Prefer the PUBLIC or PRIVATE keywords instead.
И учитывая что на лекции были  PRIVATE и PUBLIC, я прошу поправить на PUBLIC.

2020-03-25 18:14 UTC, a-badin commented on hw_1/include/process.h
> +                         const std::vector<std::string> args = {});
& кажется забыли

2020-03-25 18:14 UTC, a-badin commented on hw_1/lib/CMakeLists.txt
> +target_link_options(${LIB_NAME} PUBLIC -g3)
Получается даже в релизе будет -g3

2020-03-25 18:14 UTC, a-badin commented on hw_1/src/main.cpp
> +            std::vector<char> vec(s.size());
возьмите std::string там гарантируется 0 в конце data() + cout умеет его выводить

2020-03-26 10:08 UTC, myjupyter commented on hw_1/lib/CMakeLists.txt
> +target_link_options(${LIB_NAME} PUBLIC -g3)
++

2020-03-26 10:09 UTC, myjupyter commented on hw_1/include/process.h
> +                         const std::vector<std::string> args = {});
++

2020-03-26 10:10 UTC, myjupyter commented on hw_1/CMakeLists.txt
> +target_link_libraries(${TARGET_NAME} LINK_PUBLIC ${LIB_NAME})
++

2020-03-26 10:18 UTC, myjupyter commented on hw_1/src/process.cpp
> +            argv.push_back(const_cast<char*>(arg.c_str()));
++

2020-03-26 11:06 UTC, myjupyter commented on hw_1/src/main.cpp
> +            std::vector<char> vec(s.size());
++

2020-03-26 18:22 UTC, merged