Hw 3
myjupyter/AdvCpp pull request #3
Opened 2020-04-01 16:05 UTC by myjupyter

2020-04-01 16:18 UTC, myjupyter commented
Я немного реализовал не так, как было дано по схеме. Хотел бы как-нибудь улчшить после всех исправлений, подскажите, пожалуйста, что можно сделать.

2020-04-02 12:30 UTC, a-badin requested changes

2020-04-02 12:30 UTC, a-badin commented on hw_3/include/socket.h
> +        explicit Socket(int socket);
Как только вы вынесли наружу детали реализации, вы тут же берете себе проблем на проверку, что за число вам передали.

2020-04-02 12:30 UTC, a-badin commented on hw_3/src/socket.cpp
> +        std::swap(sock_, socket.sock_);
у вас метод не swap, а move assing, вам нужно не поменять "кишки" местами, а выдернуть их. 
Свой сокет нужно сначала закрыть, на его место поставить socket.sock_, а socket.sock_ поставить невалидный сокет

2020-04-02 12:30 UTC, a-badin commented on hw_3/src/socket.cpp
> +        state_ = socket.state_;
Состония соответственно socket нужно выставить невалидные

2020-04-02 12:30 UTC, a-badin commented on hw_3/src/socket.cpp
> +        std::cout << 2 << std::endl;
Наверное лишнее

2020-04-02 12:30 UTC, a-badin commented on hw_3/src/socket.cpp
> +    ::close(sock_);
Я могу вызвать close два раза и будет ошибка, но это еще пол беды.
Номер sock_ может получить какой-нибудь новый файл, и тогда Socket как минимум его закроет в деструкторе

2020-04-02 12:30 UTC, a-badin commented on hw_3/src/socket.cpp
> +    if (is_blocking_ ^ to_block) {
Лучше использовать явное сравнение через !=

2020-04-02 12:30 UTC, a-badin commented on hw_3/src/socket.cpp
> +        state_ = Socket::DISCONNECT;
Предлагаю кинуть исключение, иначе в каком-нибудь цикле придется проверять статус сокета

2020-04-02 12:30 UTC, a-badin commented on hw_3/include/connection_tcp.h
> +#include <socket.h>
системный в <>, свои в ""
https://gcc.gnu.org/onlinedocs/cpp/Search-Path.html

2020-04-02 12:30 UTC, a-badin commented on hw_3/include/ip_address.h
> +        sockaddr_in addr;
дэш

2020-04-02 12:30 UTC, a-badin commented on hw_3/src/ip_address.cpp
> +constexpr uint16_t DEFAULT_PORT = 44444;
Ну это прямо очень странно навязывать какой-то порт
Константы должны быть static

2020-04-02 12:30 UTC, a-badin commented on hw_3/src/ip_address.cpp
> +    if (!isValidAddr(address)) {
Вы можете сразу заполнить sockaddr_in через inet_aton и не проверять isValidAddr, будет на один вызов меньше

2020-04-02 12:30 UTC, a-badin commented on hw_3/include/server_tcp.h
> +class ServerTcp : public Socket {
Вот это нарушение приница подстановки Барбары Лисков из второй лекции.
Ваш сервер не может в полной мере работать как Socket, в него нельзя писать/читать

2020-04-02 12:30 UTC, a-badin commented on hw_3/include/server_tcp.h
> +        std::size_t write(const void* data, std::size_t size) = delete;
= delete не спасет вас, если я положу ServerTcp в указатель на Socket

2020-04-02 12:30 UTC, a-badin commented on hw_3/src/server_tcp.cpp
> +const uint16_t MAX_CONNECTIONS = 0xffff;
static, или еще моднее анонимный namespace

2020-04-02 12:30 UTC, a-badin commented on hw_3/src/server_tcp.cpp
> +    return Socket::ERROR;
Пользуйтесь исключениями

2020-04-02 12:30 UTC, a-badin commented on hw_3/src/connection_tcp.cpp
> +    setSocketStatus(
Вот это абсолютно не читаемо, в приоритете должна быть читаемость кода для другого программиста

2020-04-02 12:30 UTC, a-badin commented on hw_3/src/connection_tcp.cpp
> +            ) == -1 ? Socket::ERROR : Socket::OK
Кидайте исключение, или коды ошибок или исключения, что то одно

2020-04-02 12:30 UTC, a-badin commented on hw_3/src/server.cpp
> +#define BUFFER_SIZE 1024
1998 давно закончился, есть constexpr

2020-04-02 12:30 UTC, a-badin commented on hw_3/src/server.cpp
> +            while (Network::Socket::OK == server.accept(client)) {
Вот тут бы с исключениями, код был бы проще

2020-04-02 12:30 UTC, a-badin commented on hw_3/src/server.cpp
> +                    s.resize(BUFFER_SIZE);
Можно сразу внести в конструтор

2020-04-02 12:30 UTC, a-badin commented on hw_3/src/server.cpp
> +                    client.write(s.data(), len);
writeExact

2020-04-02 12:30 UTC, a-badin commented on hw_3/include/socket.h
> +        enum SockStatus{
У вас для ошибок и для кодов возврата используется один и тот же тип, легко запутаться

2020-04-02 12:30 UTC, a-badin commented on hw_3/src/server_tcp.cpp
> +        return Socket::RECONNECT;
При вызове скорее всего будут ловить Socket::OK

2020-04-02 12:30 UTC, a-badin commented on hw_3/src/client.cpp
> +                con.write(s.data(), s.size());
writeExact

2020-04-02 12:30 UTC, a-badin commented on hw_3/src/client.cpp
> +                con.read(res.data(), res.size());
readExact, если знаете сколько должны вернуть

2020-04-03 11:31 UTC, myjupyter commented on hw_3/include/connection_tcp.h
> +#include <socket.h>
++

2020-04-03 11:31 UTC, myjupyter commented on hw_3/include/server_tcp.h
> +class ServerTcp : public Socket {
++

2020-04-03 11:33 UTC, myjupyter commented on hw_3/include/server_tcp.h
> +        std::size_t write(const void* data, std::size_t size) = delete;
++

2020-04-03 11:34 UTC, myjupyter commented on hw_3/src/server_tcp.cpp
> +const uint16_t MAX_CONNECTIONS = 0xffff;
++

2020-04-03 11:34 UTC, myjupyter commented on hw_3/src/connection_tcp.cpp
> +    setSocketStatus(
++

2020-04-03 11:40 UTC, myjupyter commented on hw_3/src/server.cpp
> +                    s.resize(BUFFER_SIZE);
++

2020-04-03 11:40 UTC, myjupyter commented on hw_3/src/server.cpp
> +                    client.write(s.data(), len);
++

2020-04-03 11:41 UTC, myjupyter commented on hw_3/src/client.cpp
> +                con.write(s.data(), s.size());
++

2020-04-03 11:41 UTC, myjupyter commented on hw_3/src/client.cpp
> +                con.read(res.data(), res.size());
++

2020-04-03 11:42 UTC, myjupyter commented on hw_3/src/server.cpp
> +#define BUFFER_SIZE 1024
++

2020-04-03 12:07 UTC, myjupyter commented on hw_3/src/socket.cpp
> +    if (is_blocking_ ^ to_block) {
++

2020-04-03 12:10 UTC, myjupyter commented on hw_3/src/socket.cpp
> +    ::close(sock_);
++

2020-04-03 12:10 UTC, myjupyter commented on hw_3/src/socket.cpp
> +        std::cout << 2 << std::endl;
++

2020-04-03 12:11 UTC, myjupyter commented on hw_3/src/socket.cpp
> +        state_ = socket.state_;
++

2020-04-03 12:52 UTC, myjupyter commented on hw_3/src/socket.cpp
> +        std::swap(sock_, socket.sock_);
++

2020-04-03 12:53 UTC, myjupyter commented on hw_3/include/socket.h
> +        explicit Socket(int socket);
++

2020-04-03 13:03 UTC, myjupyter commented on hw_3/src/ip_address.cpp
> +constexpr uint16_t DEFAULT_PORT = 44444;
++

2020-04-03 13:35 UTC, myjupyter commented on hw_3/src/connection_tcp.cpp
> +            ) == -1 ? Socket::ERROR : Socket::OK
++

2020-04-03 14:01 UTC, myjupyter commented on hw_3/src/server.cpp
> +            while (Network::Socket::OK == server.accept(client)) {
++

2020-04-03 14:24 UTC, myjupyter commented on hw_3/include/socket.h
> +        enum SockStatus{
++

2020-04-03 14:31 UTC, myjupyter commented on hw_3/src/server_tcp.cpp
> +        return Socket::RECONNECT;
++

2020-04-03 14:32 UTC, myjupyter commented on hw_3/src/socket.cpp
> +        state_ = Socket::DISCONNECT;
Не кидаю исключение, проверяю статус в сокета

2020-04-03 14:33 UTC, myjupyter commented on hw_3/include/ip_address.h
> +        sockaddr_in addr;
++

2020-04-03 14:34 UTC, myjupyter commented on hw_3/src/server_tcp.cpp
> +    return Socket::ERROR;
++

2020-04-05 16:59 UTC, a-badin approved these changes
В 4 ой домашке сделайте свой класс на исключения

2020-04-05 16:59 UTC, a-badin commented on hw_3/include/socket.h
> +#include <errno.h>
Практичекски все не нужно

2020-04-05 16:59 UTC, a-badin commented on hw_3/src/socket.cpp
> +    close();
Он же у вас пустой сейчас, зачем его закрывать

2020-04-05 17:00 UTC, merged