Hw 5
myjupyter/AdvCpp pull request #5
Opened 2020-04-17 10:54 UTC by myjupyter

2020-04-21 08:56 UTC, a-badin requested changes
Если вам понравится идея с возвратом из map копий элементов, вместо ссылок. Тогда вы можете сделать свой map таким чтобы он принимал std::string, тогда вся работа с shared memory и аллокаторами останется инкапсулированной в  реализации map

2020-04-21 08:56 UTC, a-badin commented on hw_5/include/allocator.h
> +        Allocator(const Allocator<U>& alloc)
Верхний метод попадает в этот

2020-04-21 08:56 UTC, a-badin commented on hw_5/src/shared_memory.cpp
> +    auto* semaphore_ptr = new (reinterpret_cast<sem_t*>(p + 2)) sem_t;
semaphore_ptr = reinterpret_cast<sem_t*>(p + 2), это же pod

2020-04-21 08:56 UTC, a-badin commented on hw_5/include/allocator.h
> +            typedef Allocator<U> other;
это делает за вас std::allocator_traits

2020-04-21 08:56 UTC, a-badin commented on hw_5/include/semaph.h
> +        Semaphore(sem_t* init_addres, int init_value = 1, bool shared = false);
На самом деле странный конструктор, в который передается адрес где создать объект. Привычнее тогда хранить в классе значение sem_t а весь Semaphore создавать через placement new в Map

2020-04-21 08:56 UTC, a-badin commented on hw_5/src/shared_memory.cpp
> +SharedMemory::SharedMemory(void* ptr, std::size_t n_byte)
Почему бы тогда не создавать mmap прямо тут, класс называется SharedMemory странно что он не владеет mmap'ом с которым ассоциирован

2020-04-21 08:56 UTC, a-badin commented on hw_5/include/shared_map.h
> +        shared_shptr<value_type> memory_;
Семафор у вас не копируется, я думаю сам Map тоже не предполагается к копированию.
В этом случае shared_ptr тут необоснован, так как владением memory всегда занимается Map и ни с кем не делится. Был бы смысл, если бы аллокаторы держали ссылку на memory не по значению, а по shared_ptr, Тогда SharedString могли бы жить отдельно от Map

2020-04-21 08:56 UTC, a-badin commented on hw_5/include/shared_map.h
> +    class Alloc = Allocator<std::pair<const Key, T> >
я думаю можно было бы этот параметр убрать, у вас достаточно специфичный аллокатор, врядли его будут переопределять

2020-04-21 08:56 UTC, a-badin commented on hw_5/include/shared_map.h
> +        T& at(const Key& key) {
С точки зрения общей концепции map который можно пользоваться из разных процессов. Возврат по ссылке не очень полезен, так как вы сразу получаете race condition. Я бы возвращал тут копию

2020-04-21 08:56 UTC, a-badin commented on hw_5/example/main.cpp
> +        map.insert({1, String("df", map.get_allocator())});
Такие строки получается становятся невалидными как только исчезнет Map. Метод get_allocator довольно странный

2020-04-22 11:57 UTC, myjupyter commented on hw_5/include/shared_map.h
> +        shared_shptr<value_type> memory_;
++

2020-04-22 12:44 UTC, myjupyter commented on hw_5/include/shared_map.h
> +    class Alloc = Allocator<std::pair<const Key, T> >
++

2020-04-23 17:21 UTC, myjupyter commented on hw_5/src/shared_memory.cpp
> +    auto* semaphore_ptr = new (reinterpret_cast<sem_t*>(p + 2)) sem_t;
++

2020-04-23 17:21 UTC, myjupyter commented on hw_5/src/shared_memory.cpp
> +SharedMemory::SharedMemory(void* ptr, std::size_t n_byte)
++

2020-04-23 17:21 UTC, myjupyter commented on hw_5/include/shared_map.h
> +        T& at(const Key& key) {
++

2020-04-23 17:21 UTC, myjupyter commented on hw_5/example/main.cpp
> +        map.insert({1, String("df", map.get_allocator())});
++

2020-04-25 13:02 UTC, myjupyter commented on hw_5/include/semaph.h
> +        Semaphore(sem_t* init_addres, int init_value = 1, bool shared = false);
++

2020-04-25 13:52 UTC, myjupyter commented on hw_5/include/allocator.h
> +        Allocator(const Allocator<U>& alloc)
++

2020-04-25 13:52 UTC, myjupyter commented on hw_5/include/allocator.h
> +            typedef Allocator<U> other;
++

2020-04-28 07:18 UTC, a-badin requested changes
Решаем вопрос с деструктором + конвертирование std::string -> ShString, так как у нас нет дефолтного аллокатора

2020-04-30 16:48 UTC, a-badin approved these changes
Я вам предлагаю больше не терять на это времени. Программировать шаблоны дело муторное а в стремлении к совершенству можно никогда не дойти до точки. Код работает, реализация инкапсулирована, всё правильно лочится.

2020-04-30 16:48 UTC, a-badin commented on hw_5/include/allocator.h
> +        Allocator()
Вроде обсудили что он не нужен

2020-04-30 16:48 UTC, a-badin commented on hw_5/include/shared_map.h
> +        using rebind_key       = rebind<Key>::type;
вот эти алиасы можно было бы везде и заменить в том же value_type

2020-04-30 16:48 UTC, a-badin commented on hw_5/include/shared_map.h
> +            return T(map_->operator[](std::move(rebind_key{key, alloc})));
std::move не нужен так как rebind_key и так rvalue
T( тоже можно убрать, у вас T прописан в return type

2020-04-30 16:48 UTC, a-badin commented on hw_5/include/shared_map.h
> +        T operator[](Key&& key) {
Вот это переопределение не нужно, даже если вы хотите менять key, например, чтобы забрать у него буфер через move, этот буфер вам не нужен так как вы делаете копию в шаред memory. Значит перемещать буфер key вам не нужно, значит можифицировать key вы не будете, значит вам хватит const Key& key

2020-04-30 16:48 UTC, a-badin commented on hw_5/include/shared_map.h
> +                    [this] (const false_value_type& value) { this->map_->operator[](rebind_key{value.first, this->alloc}) = value.second;},
Вот это конечно самое страшное в этой реализации. У вас эти 4 вызова повторяют одну и туже логику, для false_value_type вы вызываете метод как есть, а для value_type кастите его с аллокатором, тут бы хватило одного методо convert и перегрузки

2020-04-30 16:48 UTC, merged